# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
<<<<<<< HEAD
  secret_key_base: 1d8b7ab058aa065fc53ae3f718097fb8be11a8f83feed04a6109fcb075d24165c1558529bfcb02e907a49b964ee6a52829174f094d5ee89c7446d3cda5913946

test:
  secret_key_base: 82eacf8e638ce9eaec5772c4a8d7be1c1a08e699a20d52908772b2c8f4c8086c1e9b5ae3c85d2e6e505c20812ca8a9e0b106838b31fae068ac4d14e0f6fc2e97
=======
  secret_key_base: 76e59058117f7101eabe69779f772b99a46584a29ab7619cb6bf163a16023c7f644547189ba946afd257227c405b326a889adfe990ffe33521221976324cc7b4

test:
  secret_key_base: a0d57652c8f5a0fb680774877049fe97d939d1c84b941ad07167ad48b2889e6e3de8034daad6c19e418c115729c06e2039d919d3cb441c46493e04e38190a923
>>>>>>> b8061cee3e3edc192d59f9f6c9bfa903be8238a3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
